name: Run Tests

on: push
jobs: 
  setup_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.6'

      - name: Install Dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Run tests
        run: pytest

  deploy:
    runs-on: ubuntu-latest
    needs: setup_test
    if: 
    steps:
      - name: Install sshpass
        run: sudo apt install sshpass

      - name: sshpass -p ${{ secrets.PASSWORD }} ssh root@${{secrets.HOST}} "bash execute.sh"
               

        
