name: Run Tests

on: push
jobs: 
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.6'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest
      
      - name: Install sshpass
        run: sudo apt install sshpass

      - name: Connect to VPS with sshpass and execute bash script
        run: sshpass -p ${{ secrets.PASSWORD }} ssh root@${{ secrets.HOST }} "bash execute.sh"
        
