name: Run Tests

on: push
jobs: 
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.6'

      - name: Install Dependencies
        run: pip install -r requirements.txt
        
      - name: Run tests
        run: pytest

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Install sshpass
        run: sudo apt install sshpass

      - name: SSHPASS Github Action
        # You may pin to the exact commit or the version.
        # uses: matheusvanzan/sshpass-action@1e96f05518c2e99d17587ee85fa4d64c1612d0f1
        uses: matheusvanzan/sshpass-action@v1
        with:
          # SSHPASS host
          host: ${{ secrets.HOST }}
          # SSHPASS username
          username: "root"
          # SSHPASS password
          password: ${{ secrets.PASSWORD }}
          # SSHPASS commands to run
          run: bash execute.sh
               

        
